### ISSUE TITLE
Refactor application and state package

### ISSUE THREAD

**Issue by vgjm** [h8r-dev/heighliner#172]
See helm [`driver`](https://github.com/helm/helm/blob/main/pkg/storage/driver/driver.go) package. We should make our state package like that. Basically, we need a storage `Driver` interface for future compatibility of other storage backend (e.g. S3). And we need an new `Application` struct to represent the status of our applications, which combine the information of current Output, TFProvider and Status.

The storage `Driver` interface looks like this
```
type Driver interface {
	Creator
	Updator
	Deletor
	Queryor
	Name() string
}
type Creator interface {
	Create(key string, apl *app.Application) error
}

type Updator interface {
	Update(key string, apl *app.Application) error
}

type Deletor interface {
	Delete(key string) (*app.Application, error)
}

type Queryor interface {
	Get(key string) (*app.Application, error)
	List(filter func(*app.Application) bool) ([]*app.Application, error)
	Query(labels map[string]string) ([]*app.Application, error)
}
```

> note: The above `Application` is not the current `app.Application` in the app package.

We need to design our `Application` struct more carefully. This should be the core resource managed by hln in future. (just like helm release).

@xinxinh2020 @hongchaodeng What about this?

**Comment by xinxinh2020** [comment]
I think we should store more information about heighliner application, such as which stack it uses. The information can be used for more advanced operations on application, such as `update` or `upgrade`.
In terms of design，maybe we can make it progressively. What information `hln` need，we add it to the state.
For `Application`，i think we don't have to wrap all information into just one struct. We just need to make sure we can get the information we need conveniently. Struct is not so important in go.

**Comment by vgjm** [comment]
> In terms of design，maybe we can make it progressively. What information `hln` need，we add it to the state. For `Application`，i think we don't have to wrap all information into just one struct. We just need to make sure we can get the information we need conveniently. Struct is not so important in go.

Sound reasonable. We don't need use one single struct that contains all info. My point is we need application struct to connect and decouple output and storage.

**Comment by hongchaodeng** [comment]
Sounds good!

FYI, it is called `Queryer`
