### ISSUE TITLE
[Bug]:  use rootless buildkit.

### ISSUE THREAD

**Issue by 92hackers** [h8r-dev/heighliner#209]
buildkit `master` image tested successed.

**Comment by 92hackers** [comment]
#210 Just update buildkit image tag from `master-rootless` to `master`, and stack still needs to use `rootless` buildkit.

**Comment by vgjm** [comment]
> 

Why use rootless?

**Comment by 92hackers** [comment]
Currently, `security` is not an critical issue, just keep this issue open.

**Comment by hongchaodeng** [comment]
Dagger currently relies on privileged container. See:
- https://github.com/dagger/dagger/issues/1588
- https://docs.dagger.io/1223/custom-buildkit/#running-a-custom-buildkit-container-in-docker

We can only use rootless buildkit after dagger supports it.
