### ISSUE TITLE
Fail to launch the sample project

### ISSUE THREAD

**Issue by flyforfreedom** [h8r-dev/heighliner#238]
I followed the installation guide to try the "Hello World" sample, but command "hln up hello-world -s sample -i" show me the error message below:

"cmd/root.go:126	no schema found in current satck: open /root/.cache/heighliner/sample/schemas/schema.yaml: no such file or directory"

I couldn't find file "schema.yaml" anywhere within this project, and could not step forward.

**Comment by hongchaodeng** [comment]
We are launching a new version at the moment. Let me contact you via wechat~

**Comment by ryanwuer** [comment]
> We are launching a new version at the moment. Let me contact you via wechat~

Same problem. How can i get contacted with you by wechat?
